- fixtures/no-paths.yml
- mixin.go
- mixin_test.go
Bugfix/Issue #12: Specs with empty paths field create nil .Paths which panics Mixin() 
paths: 
PR for go-swagger/go-swagger #1005 needs this in order avoid an extra vendoring bump for analysis pkg.
> Fix Mixin panic on nil Paths and add test for it. Issue #12

- fixtures/empty-paths.json
- mixin.go
- mixin_test.go
The un-initialized data structs resulted from from loading an ~empty primary spec.
Thanks for heads up on this added in issue #12
> fixed some NPEs resulting from un-initialized data structs

- flatten.go
fixes go-swagger/go-swagger#1322
> uniqify definitions with same characters regardless of lower/upper case

- flatten.go
- flatten_test.go
https://github.com/go-swagger/go-swagger/issues/1336
When creating names for complex inline schemas, don't create a separate name
for an array of objects within an object.  It breaks the JSON marshalling
and unmarshalling if that array is of objects of a polymorphic type.
Signed-off-by: Greg Marr <greg.marr@autodesk.com>
> JSON broken for object w/array of polymorphic types.

- fixer.go
- fixtures/other-mixin.yml
- fixtures/securitydef.yml
- fixtures/widget-crud.yml
- flatten.go
- flatten_test.go
- mixin.go
- mixin_test.go
* Extends mixin spec to top level definitions: schemes, tags, produces, consumes, securityDefinition and security requirements
* Refactored mixin and extended UT
* Moved spec fix to dedicated source file
* A little linting after a gometalinter pass
* Added missing copyrights in source
Contributes to:
* go-swagger/go-swagger#1471
> Extends mixin

- schema.go
- schema_test.go
Fix edge case with tuple definition with a single element
We must check tuple using .Schemas != nil rather than (*SchemaOrArray) Len().
The following definition:
```yaml
type: array
items:
- type: integer
``` 
should be considered a tuple and not an array.
> NOTE: this story about tuples is always a bit edgy. So I confirmed my views by validating this using `ajv`
> Fix array vs tuple detection

- schema.go
- schema_test.go
I just forgot to correctly process and test the case:
```yaml
type: array
items: {}
```
> Last minute fix on IsTuple

- .golangci.yml
- fixtures/bugs/1602/fixture-1602-1.yaml
- fixtures/bugs/1602/fixture-1602-2.yaml
- fixtures/bugs/1602/fixture-1602-3.yaml
- fixtures/bugs/1602/fixture-1602-4.yaml
- fixtures/bugs/1602/fixture-1602-5.yaml
- fixtures/bugs/1602/fixture-1602-full.yaml
- fixtures/bugs/1602/other-invalid-pointers.yaml
- flatten.go
- flatten_test.go
- schema.go
- schema_test.go
~~Pointer inference is more tolerant and warns~~  
_report error_ about likely mishaps
with $ref to non schema objects in spec.
More edge case UT for schema analysis (explore error cases).
Extended golangci limit for cyclomatic check.
> NOTE: go-swagger/go-swagger#1602 is actually caused by an invalid spec.
> Nonetheless, this PR makes the analysis job more ~~resilient, and~~ informative about what
> has gone wrong.
> Fix go-swagger/go-swagger#1602

- .gitignore
- .travis.yml
- fixtures/bugs/1602/fixture-1602-6.yaml
- fixtures/bugs/1614/gitea.yaml
- fixtures/bugs/1621/definitions.yaml
- fixtures/bugs/1621/fixture-1621.yaml
- fixtures/bugs/1621/parameters.yaml
- fixtures/bugs/1621/responses.yaml
- flatten.go
- flatten_test.go
- hack/coverage
- internal/path_unescape_test.go
- internal/post_go18.go
- internal/pre_go18.go
Fix flatten with pointers containing escaped chars (e.g. '{}')
Fixed undue duplicate name detection when resolving remote refs
Improves behavior in edge cases where schemas points to responses
or parameters.
This makes the flatten behavior consistent with swagger validate.
* now unmarshalls the struct as a schema: if this works, flattening
moves on, with a warning to the user (as this is valid but most
likely unintended)
* improves go-swagger/go-swagger#1602 and go-swagger/go-swagger#1614
* contributes go-swagger/go-swagger#1621
* Expand schemas when $ref'ed to (shared) responses or parameters
> Fix flatten with pointers containing escaped chars

- analyzer.go
- analyzer_test.go
- fixtures/enums.yml
- flatten.go
This feature is going to be used to detect conflicts with generated enum names in go-swagger
- also fix race condition in flatten (which is of no practical use atm, since spec expand is not parallelizable)
> Add enum analysis

- .codecov.yml
- .golangci.yml
- analyzer.go
- fixtures/bugs/1851/definitions-3.yaml
- fixtures/bugs/1851/definitions-31.yaml
- fixtures/bugs/1851/definitions.yaml
- fixtures/bugs/1851/fixture-1851-2.yaml
- fixtures/bugs/1851/fixture-1851-3.yaml
- fixtures/bugs/1851/fixture-1851.yaml
- fixtures/bugs/1851/remote/definitions-32.yaml
- fixtures/external_definitions_valid.yml
- flatten.go
- flatten_test.go
Flatten now resolves remote $ref iteratively, without expanding.
This allows for keeping definitions unexpanded and reused by referers positioned at different nesting levels.
Contributes go-swagger/go-swagger#1851
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
> Iterate remote ref resolve

- fixtures/empty-props.yml
- fixtures/swagger-props.yml
- mixin.go
- mixin_test.go
added support for merging top-level info and vendor extensions at top level and in info struct
Contributes go-swagger/go-swagger#1886
Contributes go-swagger/go-swagger#1965
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
> fix(mixin): added support for merging top-level info

- analyzer.go
- flatten.go
This allows to reduce the memory consumption during loads.Analyzed
significantly.
before:
```
2076.76kB 21.23% 21.23%  2076.76kB 21.23%  github.com/go-openapi/analysis.(*Spec).reset
1024.06kB 10.47% 57.11%  1024.06kB 10.47%  github.com/go-openapi/analysis.(*Spec).analyzeSchema
```
after (analyzeSchema doesn't even show up in the memory profile anymore):
```
1034.66kB 15.31% 15.31%  1034.66kB 15.31%  github.com/go-openapi/analysis.(*Spec).reset
```
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> Pass pointer to schema to (*Spec).analyzeSchema instead of copying

- schema.go
The following was found by dgryski's [semgrep-go](https://github.com/dgryski/semgrep-go) rule collection:
```
schema.go
severity:error rule:github.com.dgryski.semgrep-go.bad-nil-guard: Bad nil guard
221:		(a.schema.AdditionalProperties != nil || a.schema.AdditionalProperties.Allows)
```
Signed-off-by: Karsten Weiss <knweiss@gmail.com>
> schema.go: Fix bad nil guard

- .travis.yml
- README.md
- appveyor.yml
- internal/antest/helpers.go
* bumped go versions in CI
* reduced the travis CI matrix to run longer tests only on one arch and go version
* enriched the travis CI matrix with osx and arm64 runs
* removed golangCI badge
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
> fixed test coverage measurement issue with multiple packages 

- analysis_test/spec_test.go
This is causing parse errors such as:
yaml: line 2: found character that cannot start any token
and
yaml: line 96: found character that cannot start any token
Signed-off-by: Guillem Jover <gjover@sipwise.com>
> Remove spurious literal tab characters from YAML fixture

- .golangci.yml
Goal is to make link on master branch pass.
> Ignore varnamelen linter in ci

- .github/workflows/go-test.yml
- fixtures/bugs/1898/swagger.json
- flatten.go
- flatten_name.go
- flatten_test.go
- go.mod
- go.sum
- internal/flatten/replace/replace.go
- internal/flatten/sortref/keys.go
This PR allows for reusing schemas stored in x-... extensions of the spec, via json pointers.
We have seen some specs using such extensions to create "alternate definitions". The spec flattening canonicalizes such schemas by reintroducing them as #/definitions, so they can be consumed by codegen.
* requires: go-openapi/jsonpointer#16
* contributes: go-swagger/go-swagger#1898
> fix(flatten): allows the use of pointers to schemas in x-... extensions

- fixtures/bugs/2657/schema-flattened.yaml
- fixtures/bugs/2657/schema.json
- fixtures/expected/external-references-2.json
- flatten.go
- flatten_test.go
Whenever unused definitions are removed, some new definitions may appear as unused. This PR goes does this rabbit hole to delete all unused definitions until no unused candidate shows up.
* contributes go-swagger/go-swagger#2657
> fix(flatten): remove unused acts recursively

- fixtures/bugs/2743/not-working/minimal.yaml
- fixtures/bugs/2743/not-working/spec.yaml
- fixtures/bugs/2743/not-working/swagger/definitions.yml
- fixtures/bugs/2743/not-working/swagger/items.yml
- fixtures/bugs/2743/not-working/swagger/paths/bar.yml
- fixtures/bugs/2743/not-working/swagger/paths/foo.yml
- fixtures/bugs/2743/not-working/swagger/paths/index.yml
- fixtures/bugs/2743/not-working/swagger/paths/nested.yml
- fixtures/bugs/2743/not-working/swagger/user/index.yml
- fixtures/bugs/2743/not-working/swagger/user/model.yml
- fixtures/bugs/2743/working/spec.yaml
- fixtures/bugs/2743/working/swagger/definitions.yml
- fixtures/bugs/2743/working/swagger/items.yml
- fixtures/bugs/2743/working/swagger/paths/bar.yml
- fixtures/bugs/2743/working/swagger/paths/foo.yml
- fixtures/bugs/2743/working/swagger/paths/index.yml
- fixtures/bugs/2743/working/swagger/paths/nested.yml
- fixtures/bugs/2743/working/swagger/user/index.yml
- fixtures/bugs/2743/working/swagger/user/model.yml
- flatten_test.go
- go.mod
- go.sum
This reproduces the $ref issue with relative paths in sibling folders in responses (same applies to parameters, but not schemas).
Added a test to verify that:
* (i) the invalid path that used to work no longer does
* (ii) the valid path that used not to work now does
* contributes go-swagger/go-swagger#2743
> test(flatten): asserts that the ExpandSpec fix in spec works

- .github/workflows/auto-merge.yml
* enabled auto-merge for go-openapi minor version bumps, not just patches
> ci: auto-merge dependabot PRs

- .golangci.yml
- analyzer.go
- flatten.go
- flatten_name.go
- internal/flatten/replace/replace.go
- internal/flatten/schutils/flatten_schema.go
- mixin.go
Fixed linter config that made CI unworkable.
> Partial relinting

- analyzer.go
- analyzer_test.go
- errors.go
- flatten.go
- flatten_name.go
- internal/antest/helpers_test.go
- internal/debug/debug_test.go
- internal/flatten/replace/errors.go
- internal/flatten/replace/replace.go
- internal/flatten/sortref/keys.go
- mixin.go
- schema.go
* addressed linting issues, especially those related to non-wrapping errors: refactored all calls to fmt.Errorf()
* fixes #114: unfortunate copy paste typo in mixin.go
> Relinting (2)

- .github/workflows/auto-merge.yml
A change in github's pull request metadata disabled auto-merge for dependabot PR's.
We now use the appropriate metadata.
> Re-enacted dependabot auto-merge
